### ISSUE TITLE
Geofencing location does not "reset" after setting in/out manually at a location

### ISSUE THREAD

**Issue by TheJoeFin** [blinkupsdk/bLinkupSwiftSample#4]
Test Procedure:

Expected Behavior:
1. Test Presence Location manually set "In"
2. Test Presence Location manually set "Out"
3. Physically enter Test Presence Location - Automatically set "In"
4. Physically leave Test Presence Location - Automatically set "Out"
5. Test Presence Location manually set "In"
6. Physically enter Test Presence Location - no change
7. Physically enter Test Presence Location - Automatically set "Out"

Actual Behavior
1. 1. Test Presence Location manually set "In"
2. Test Presence Location manually set "Out"
3. Physically enter Test Presence Location - no change
4. Physically leave Test Presence Location - no change
5. Test Presence Location manually set "In"
6. Physically enter Test Presence Location - no change
7. Physically enter Test Presence Location - no change

@chasok can you look into where the issue might be here? Is this an issue with the backend, Swift SDK, or the Swift Sample App?

**Comment by chasok** [comment]
sdk, in progress
